models:
  idea_status:
    - 
      title_multiloc: statuses.proposed
      ordering: 100
      code: proposed
      color: '#84939E'
      description_multiloc: statuses.proposed_description
    - 
      title_multiloc: statuses.under_consideration
      ordering: 200
      code: under_consideration
      color: '#29ABD0'
      description_multiloc: statuses.under_consideration_description
    - 
      title_multiloc: statuses.accepted
      ordering: 300
      code: accepted
      color: '#17C37B'
      description_multiloc: statuses.accepted_description
    - 
      title_multiloc: statuses.rejected
      ordering: 400
      code: rejected
      color: '#EF3E4A'
      description_multiloc: statuses.rejected_description
    -
      title_multiloc: statuses.implemented
      ordering: 500
      code: implemented
      color: '#B5DA23'
      description_multiloc: statuses.implemented_description
  topic:
    -
      title_multiloc: topics.infrastructure
      description_multiloc: topics.infrastructure_description
    -
      title_multiloc: topics.waste
      description_multiloc: topics.waste_description
    -
      title_multiloc: topics.mobility
      description_multiloc: topics.mobility_description
    -
      title_multiloc: topics.technology
      description_multiloc: topics.technology_description
    -
      title_multiloc: topics.economy
      description_multiloc: topics.economy_description
    -
      title_multiloc: topics.nature
      description_multiloc: topics.nature_description
    -
      title_multiloc: topics.sustainability
      description_multiloc: topics.sustainability_description
    -
      title_multiloc: topics.housing
      description_multiloc: topics.housing_description
    -
      title_multiloc: topics.culture
      description_multiloc: topics.culture_description
    -
      title_multiloc: topics.citizenship
      description_multiloc: topics.citizenship_description
    -
      title_multiloc: topics.social
      description_multiloc: topics.social_description
    -
      title_multiloc: topics.health
      description_multiloc: topics.health_description
    -
      title_multiloc: topics.sport
      description_multiloc: topics.sport_description
    -
      title_multiloc: topics.education
      description_multiloc: topics.education_description
  page:
    - &1
      title_multiloc: pages.infopage_title
      body_multiloc: pages.infopage_body
      slug: information
    - &2
      title_multiloc: pages.cookie_policy_title
      body_multiloc: pages.cookie_policy_body
      slug: cookie-policy
    - &3
      title_multiloc: pages.privacy_policy_title
      body_multiloc: pages.privacy_policy_body
      slug: privacy-policy
    - &4
      title_multiloc: pages.terms_and_conditions_title
      body_multiloc: pages.terms_and_conditions_body
      slug: terms-and-conditions
  page_link:
    - linking_page_ref: *1
      linked_page_ref: *2
      ordering: 1
    - linking_page_ref: *1
      linked_page_ref: *3
      ordering: 2
    - linking_page_ref: *1
      linked_page_ref: *4
      ordering: 3
    - linking_page_ref: *2
      linked_page_ref: *1
      ordering: 1
    - linking_page_ref: *2
      linked_page_ref: *3
      ordering: 2
    - linking_page_ref: *2
      linked_page_ref: *4
      ordering: 3
    - linking_page_ref: *3
      linked_page_ref: *1
      ordering: 1
    - linking_page_ref: *3
      linked_page_ref: *2
      ordering: 2
    - linking_page_ref: *3
      linked_page_ref: *4
      ordering: 3
    - linking_page_ref: *4
      linked_page_ref: *1
      ordering: 1
    - linking_page_ref: *4
      linked_page_ref: *2
      ordering: 2
    - linking_page_ref: *4
      linked_page_ref: *3
      ordering: 3
  project:
    - &1
      title_multiloc: projects.open_idea_project_title
      description_multiloc: projects.open_idea_project_description
      internal_role: open_idea_box
      presentation_mode: card
      process_type: continuous
      participation_method: ideation
      posting_enabled: true
      commenting_enabled: true
      voting_enabled: true
      voting_method: unlimited
      remote_header_bg_url: http://res.cloudinary.com/citizenlabco/image/upload/v1516809200/Idea_cover_qdrwa6.jpg
  project_image:
    - remote_image_url: http://res.cloudinary.com/citizenlabco/image/upload/v1516925813/open_idea_box_gaxtpy.png
      project_ref: *1
  custom_field:
    - &cfgender
      resource_type: User
      key: gender
      title_multiloc: custom_fields.gender
      input_type: select
      required: false
      ordering: 0
      enabled: true
      code: gender
    - &cfbirthyear
      resource_type: User
      key: birthyear
      title_multiloc: custom_fields.birthyear
      input_type: number
      required: false
      ordering: 1
      enabled: true
      code: birthyear
    - &cfdomicile
      resource_type: User
      key: domicile
      title_multiloc: custom_fields.domicile
      input_type: select
      required: false
      ordering: 2
      enabled: true
      code: domicile
    - &cfeducation
      resource_type: User
      key: education
      title_multiloc: custom_fields.education
      input_type: select
      required: false
      ordering: 3
      enabled: false
      code: education
  custom_field_option:
    - custom_field_ref: *cfgender
      key: male
      title_multiloc: custom_field_options.gender.male
      ordering: 0
    - custom_field_ref: *cfgender
      key: female
      title_multiloc: custom_field_options.gender.female
      ordering: 1
    - custom_field_ref: *cfgender
      key: unspecified
      title_multiloc: custom_field_options.gender.unspecified
      ordering: 2
    - custom_field_ref: *cfeducation
      key: "2"
      title_multiloc: custom_field_options.education.ISCED2
      ordering: 0
    - custom_field_ref: *cfeducation
      key: "3"
      title_multiloc: custom_field_options.education.ISCED3
      ordering: 1
    - custom_field_ref: *cfeducation
      key: "4"
      title_multiloc: custom_field_options.education.ISCED4
      ordering: 2
    - custom_field_ref: *cfeducation
      key: "5"
      title_multiloc: custom_field_options.education.ISCED5
      ordering: 3
    - custom_field_ref: *cfeducation
      key: "6"
      title_multiloc: custom_field_options.education.ISCED6
      ordering: 4
    - custom_field_ref: *cfeducation
      key: "7"
      title_multiloc: custom_field_options.education.ISCED7
      ordering: 5
    - custom_field_ref: *cfeducation
      key: "8"
      title_multiloc: custom_field_options.education.ISCED8
      ordering: 6
