version: 2
updates:
- package-ecosystem: npm
  directory: "/front"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
    - "luucvanderzee"
  reviewers:
    - "luucvanderzee"
  commit_message:
    prefix: "npm"
    include: "scope"
