name: CI
on:
  push:
    paths: ['cl2-component-library/**'] # Trigger the action when files change in the folder defined here
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Use cached node_modules
        uses: actions/cache@v3
        with:
          path: cl2-component-library/node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: cd cl2-component-library && npm ci
        env:
          CI: true

      - name: Lint
        run: cd cl2-component-library && npm run lint
        env:
          CI: true

      - name: Test
        run: cd cl2-component-library && npm run test --ci --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: cd cl2-component-library && npm run build
        env:
          CI: true
